spring.application.name=SpringBootJPADataWithRelationship
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/infyni1 
spring.datasource.username=root
spring.datasource.password=Sweety@1
#if table not present it will create based upon entity class.
spring.jpa.hibernate.ddl-auto=update 
server.port=8086
